import { buildingMap } from '~/types/game-data-types';
import { Integer } from '~/types/number-types';

export const BUILDINGS: buildingMap = {
  fields: {
    id: 1,
    name: 'Fields',
    description: 'Wheat, barley, and millet. Everything a roman citizen (and the rest) needs. ',
    costGold: 20,
    costGrain: 0,
    costStone: 0,
    goldPerSecond: 0,
    grainPerSecond: 3,
    stonePerSecond: 0,
  },
  quarry: {
    id: 2,
    name: 'Quarry',
    description: 'Procure stone for your province',
    costGold: 100,
    costGrain: 300,
    costStone: 0,
    goldPerSecond: 3,
    grainPerSecond: 0,
    stonePerSecond: 6,
  },
  bakery: {
    id: 3,
    name: 'Bakery',
    description: 'Bread is an essential part of the roman diet.',
    costGold: 1000,
    costGrain: 700,
    costStone: 600,
    goldPerSecond: 15,
    grainPerSecond: 5,
    stonePerSecond: 0,
  },
  forum: {
    id: 4,
    name: 'Forum',
    description: 'Commerce, politics and a social space. The center of day-to-day roman life.',
    costGold: 4500,
    costGrain: 0,
    costStone: 3500,
    goldPerSecond: 30,
    grainPerSecond: 10,
    stonePerSecond: 20,
  },
  smithy: {
    id: 5,
    name: 'Smithy',
    description: 'From household goods to weapons and war machinery, roman smithies are the best in the world.',
    costGold: 10000,
    costGrain: 0,
    costStone: 8000,
    goldPerSecond: 50,
    grainPerSecond: 0,
    stonePerSecond: 25,
  },
  castra: {
    id: 6,
    name: 'Castra',
    description: 'The barracks, a place to safely house your troops before any campaign.',
    costGold: 50000,
    costGrain: 0,
    costStone: 20000,
    goldPerSecond: 70,
    grainPerSecond: 0,
    stonePerSecond: 50,
  },
  temple: {
    id: 7,
    name: 'Temple',
    description: 'Place of worship for a deity of choice. Pray, make an offering. Perhaps the gods will answer.',
    costGold: 160000,
    costGrain: 30000,
    costStone: 30000,
    goldPerSecond: 100,
    grainPerSecond: 100,
    stonePerSecond: 100,
  },
} as const;

export const BUILDINGS_ARRAY = Object.values(BUILDINGS);
export const BUILDINGS_COUNT: Integer = BUILDINGS_ARRAY.length as Integer;
