import { UpgradeKeys, upgradeData } from '~/types/game-data-types';
import { Integer } from '~/types/number-types';

// Shift them around so the mundane ones come first and the Divine ones are dead last
export const UPGRADES: Record<UpgradeKeys, upgradeData> = {
  goldenEagleStandard: {
    id: 1,
    name: 'Golden Eagle Standard',
    description: 'Symbol of Rome’s might, boosts all gold earnings.',
    costGold: 100,
    costGrain: 50,
    costStone: 25,
    goldMultiplier: 2,
    grainMultiplier: 1,
    stoneMultiplier: 1,
  },
  ceresBlessing: {
    id: 2,
    name: "Ceres' Blessing",
    description: 'Goddess of agriculture smiles upon your fields.',
    costGold: 200,
    costGrain: 150,
    costStone: 75,
    goldMultiplier: 2.5,
    grainMultiplier: 1.5,
    stoneMultiplier: 1.2,
  },
  templeOfJupiter: {
    id: 3,
    name: 'Temple of Jupiter',
    description: 'Sky god grants abundant resources.',
    costGold: 300,
    costGrain: 200,
    costStone: 150,
    goldMultiplier: 3,
    grainMultiplier: 2,
    stoneMultiplier: 1.5,
  },
  aqueductExpansion: {
    id: 4,
    name: 'Aqueduct Expansion',
    description: 'Advanced engineering and clean streets increases productivity.',
    costGold: 400,
    costGrain: 300,
    costStone: 250,
    goldMultiplier: 3.5,
    grainMultiplier: 2.5,
    stoneMultiplier: 2,
  },
  vulcansForge: {
    id: 5,
    name: 'Vulcan’s Forge',
    description: 'God of fire enhances stone production.',
    costGold: 500,
    costGrain: 350,
    costStone: 350,
    goldMultiplier: 4,
    grainMultiplier: 3,
    stoneMultiplier: 2.5,
  },
  roadExpansion: {
    id: 6,
    name: 'Road Expansion',
    description: 'New roads improve trade and productivity.',
    costGold: 600,
    costGrain: 400,
    costStone: 450,
    goldMultiplier: 4.5,
    grainMultiplier: 3.5,
    stoneMultiplier: 3,
  },
  forumMarketplace: {
    id: 7,
    name: 'Forum Marketplace',
    description: 'Expanded trade boosts gold earnings.',
    costGold: 700,
    costGrain: 450,
    costStone: 550,
    goldMultiplier: 5,
    grainMultiplier: 4,
    stoneMultiplier: 3.5,
  },
  fieldOfMars: {
    id: 8,
    name: 'Field of Mars',
    description: 'Dedicated to the god of war, boosts grain.',
    costGold: 800,
    costGrain: 500,
    costStone: 650,
    goldMultiplier: 5.5,
    grainMultiplier: 4.5,
    stoneMultiplier: 4,
  },
  pantheonRenovation: {
    id: 9,
    name: 'Pantheon Renovation',
    description: 'Renovation draws crowds, increasing all income.',
    costGold: 900,
    costGrain: 600,
    costStone: 750,
    goldMultiplier: 6,
    grainMultiplier: 5,
    stoneMultiplier: 4.5,
  },
  apollosOracle: {
    id: 10,
    name: 'Apollo’s Oracle',
    description: 'Prophecies attract wealth and resources.',
    costGold: 1000,
    costGrain: 700,
    costStone: 850,
    goldMultiplier: 6.5,
    grainMultiplier: 5.5,
    stoneMultiplier: 5,
  },
} as const;

export const UPGRADES_ARRAY = Object.values(UPGRADES);
export const UPGRADES_COUNT: Integer = UPGRADES_ARRAY.length as Integer;
