export type workerKeys = 'slave' | 'agricola' | 'miner' | 'baker' | 'mercator' | 'blacksmith' | 'legionary' | 'priest';

export type workerMap = {
  [key in workerKeys]: workersData;
};

export const WORKERS: workerMap = {
  slave: {
    id: 1,
    name: 'Slave',
    description: "Multipurpose worker and someone's property. May be granted citizenship one day",
    costGold: 1,
    costGrain: 15,
    costStone: 0,
    goldPerClick: 1,
    grainPerClick: 1,
    stonePerClick: 1,
  },
  agricola: {
    id: 2,
    name: 'Agricola',
    description: 'People dedicated to the craft of the land. Actually mostly slaves. ',
    costGold: 5,
    costGrain: 50,
    costStone: 0,
    goldPerClick: 0,
    grainPerClick: 3,
    stonePerClick: 0,
  },
  miner: {
    id: 3,
    name: 'Miner',
    description: 'Workers for the mines. Ill-fated people, likely to face death. Good for the economy, though.',
    costGold: 5,
    costGrain: 50,
    costStone: 0,
    goldPerClick: 1,
    grainPerClick: 0,
    stonePerClick: 3,
  },
  baker: {
    id: 4,
    name: 'Baker',
    description: 'Keeps the people fed. Makes some good bread.',
    costGold: 30,
    costGrain: 250,
    costStone: 0,
    goldPerClick: 10,
    grainPerClick: 0,
    stonePerClick: 0,
  },
  mercator: {
    id: 5,
    name: 'Mercator',
    description: 'Sells goods. Buys goods. Makes the markets lively.',
    costGold: 1500,
    costGrain: 800,
    costStone: 0,
    goldPerClick: 10,
    grainPerClick: 30,
    stonePerClick: 10,
  },
  blacksmith: {
    id: 6,
    name: 'Blacksmith',
    description: 'Skilled worker, covers a wide array of needs of the roman people.',
    costGold: 2500,
    costGrain: 3000,
    costStone: 0,
    goldPerClick: 50,
    grainPerClick: 10,
    stonePerClick: 0,
  },
  legionary: {
    id: 7,
    name: 'Legionary',
    description: 'Soldiers, security and even builders. Legionaries are really versatile.',
    costGold: 10000,
    costGrain: 5000,
    costStone: 0,
    goldPerClick: 100,
    grainPerClick: 40,
    stonePerClick: 0,
  },
  priest: {
    id: 8,
    name: 'Priest',
    description: 'Tends to the temples, holds rituals and receives offerings',
    costGold: 20000,
    costGrain: 8000,
    costStone: 0,
    goldPerClick: 150,
    grainPerClick: 90,
    stonePerClick: 0,
  },
};
